# =============================================================
# Loss settings
# =============================================================
_target_: "torch_concepts.nn.WeightedConceptLoss"

weight: 0.8 # weight applied to concepts, (1-weight) applied to task
task_names: ${dataset.default_task_names}

fn_collection:
  _target_: "torch_concepts.nn.modules.utils.GroupConfig"
  binary: 
    _target_: "torch.nn.BCEWithLogitsLoss"
  categorical: 
    _target_: "torch.nn.CrossEntropyLoss"
  # continuous: 
    # ... not supported yet
