batch_size: 512

seed: ${seed}              # train/val/test split seed
generation_seed: ${dataset.seed}    # dataset generation seed

val_size: 0.1
test_size: 0.2

concept_subset: null # if null, use all concepts