defaults:
  - _commons
  - _commons_bnlearn
  - _self_

datamodule:
  _target_: torch_concepts.data.datamodules.bnlearn.BnLearnDataModule

  name: andes

  autoencoder_kwargs:
    latent_dim: 1024

default_task_names: [SNode_151]
