defaults:
  - _commons
  - _commons_bnlearn
  - _self_

name: pigs

datamodule:
  _target_: torch_concepts.data.datamodules.bnlearn.BnLearnDataModule

  name: pigs

  autoencoder_kwargs:
    latent_dim: 1024

default_task_names: [p82265990]
