defaults:
  - _commons
  - _commons_bnlearn
  - _self_

_target_: torch_concepts.data.datamodules.bnlearn.BnLearnDataModule

name: pigs

default_task_names: [p82265990]

autoencoder_kwargs:
  latent_dim: 1024