defaults:
  - metrics: _default
  - _self_


encoder_kwargs:
  hidden_size: 64
  n_layers: 1
  activation: leaky_relu
  dropout: 0.5


# learner parameters

variable_distributions:
  discrete_card1: 
    path: "torch.distributions.RelaxedBernoulli"
    kwargs:
      temperature: 0.1
  discrete_cardn: 
    path: "torch.distributions.RelaxedOneHotCategorical"
    kwargs:
      temperature: 0.1
      # num_classes: to be set dynamically for each concept
  continuous_card1: 
    path: "torch_concepts.distributions.Delta"
  continuous_cardn: 
    path: "torch_concepts.distributions.Delta"


optim_class:
  _target_: "hydra.utils.get_class"
  path: "torch.optim.AdamW"
optim_kwargs:
  lr: 0.00075


summary_metrics: true
perconcept_metrics: ${dataset.default_task_names}


# TODO: implement this
# train_interv_prob: 0.1
# test_interv_policy: nodes_true # levels_true, levels_pred, nodes_true, nodes_pred, random
# test_interv_noise: 0.
