defaults:
  - metrics: _default
  - _self_


# =============================================================
# Encoder (features -> latent space) settings
# =============================================================
latent_encoder: null # default is MLP
latent_encoder_kwargs:
  hidden_size: 64
  n_layers: 1
  activation: leaky_relu
  dropout: 0.5


# =============================================================
# Concept distribution configs
# =============================================================
variable_distributions:
  discrete_card1: 
    path: "torch.distributions.RelaxedBernoulli"
    kwargs:
      temperature: 0.1
  discrete_cardn: 
    path: "torch.distributions.RelaxedOneHotCategorical"
    kwargs:
      temperature: 0.1
      # num_classes: to be set dynamically for each concept
  continuous_card1: 
    path: "torch_concepts.distributions.Delta"
  continuous_cardn: 
    path: "torch_concepts.distributions.Delta"


# =============================================================
# Optimizer settings
# =============================================================
optim_class:
  _target_: "hydra.utils.get_class"
  path: "torch.optim.AdamW"
optim_kwargs:
  lr: 0.00075


# =============================================================
# Scheduler settings
# =============================================================
# scheduler_class: 
#   _target_: "hydra.utils.get_class"
#   path: "torch.optim.lr_scheduler.ReduceLROnPlateau"
# scheduler_kwargs:
#   factor: 0.2


# =============================================================
# Metrics settings
# =============================================================
# tracking of summary metrics for each concept type
summary_metrics: true
# tracking of metrics for each individual concept 
# `true` for all concepts, list of concept names, or `false` for none
perconcept_metrics: ${dataset.default_task_names}

# TODO: implement this
# train_interv_prob: 0.1
# test_interv_policy: nodes_true # levels_true, levels_pred, nodes_true, nodes_pred, random
# test_interv_noise: 0.
