defaults:
  - _commons
  - _self_
  
# wrapper for 'joint' training mode
_target_: "torch_concepts.nn.ConceptBottleneckModel"

task_names: ${dataset.default_task_names}

inference:  
  _target_: "torch_concepts.nn.DeterministicInference"
  _partial_: true