defaults:
  - _commons
  - _self_
  
_target_: "torch_concepts.nn.ConceptBottleneckModel"

task_names: ${dataset.default_task_names}

training: "joint" # "joint", "sequential", "independent"

inference:  
  _target_: "torch_concepts.nn.DeterministicInference"
  _partial_: true