defaults:
  - _commons
  - _self_
  
_target_: "torch_concepts.nn.ConceptEmbeddingModel_Independent"

task_names: ${dataset.default_task_names}

exogenous_size: 4

inference: 
  _target_: "torch_concepts.nn.DeterministicInference"
  _partial_: true