defaults:
  - _default
  - _self_

hydra:
  job:
    name: benchmark
  sweeper:
    params:
      seed: 1,2,3,4,5
      dataset: dag_asia, dag_sachs, dag_insurance, dag_alarm
      model: cbm, cem, c2bm
      loss: standard

dataset:
  batch_size: 2048

model:
  optim_kwargs:
    lr: 0.005
  latent_encoder_kwargs:
    hidden_size: 128
    n_layers: 1
    activation: leaky_relu
    dropout: 0.

metrics:
  summary: true
  per_concept: true

trainer:
  max_epochs: 200
  patience: 20

debug: false