defaults:
  - _default
  - _self_

hydra:
  job:
    name: test
  sweeper:
    # standard grid search
    params:
      seed: 42
      dataset: cub, cub_incomplete, awa2, awa2_incomplete
      model: cbm, cem
      model.train_inference._target_:
        torch_concepts.nn.DeterministicInference
      # --- inference params
      # +model.train_inference.detach: false, true
      # +model.train_inference.p: 0.4
      loss: standard
      # --- weighted loss params
      # loss.concept_weight: 10
      # loss.task_weight: 1

dataset:
  batch_size: 2048
  # concept_subset: ['Attractive', 'Bald', 'Big_Nose', 'Black_Hair']  # for celeba

model:
  optim_kwargs:
    lr: 0.01
  latent_encoder_kwargs:
    hidden_size: 128
    n_layers: 1
    activation: leaky_relu
    dropout: 0.
  # embedding_size: 8  # for embedding models

metrics:
  summary: true
  per_concept: true # true or ${dataset.default_task_names}

trainer:
  # logger: wandb
  # log_model: true   # whether to save checkpoint on wandb
  save_top_k: 1.    # whether to save checkpoint locally
  max_epochs: 20
  patience: 20

matmul_precision: medium

debug: true # whether to add run to the analysis registry 

notes: test