defaults:
  - _default
  - _self_

hydra:
  job:
    name: test
  sweeper:
    # standard grid search
    params:
      seed: 1
      dataset: asia
      model: cbm
      # loss: weighted
      # loss.weight: 0.99

model:
  summary_metrics: true
  perconcept_metrics: true #${dataset.default_task_names}
  # train_interv_prob: 0.8
  # test_interv_noise: 0.8   # for bndatasets only
  optim_kwargs:
    lr: 0.001

trainer:
  logger: null
  devices: [0]
  max_epochs: 20
  patience: 30

matmul_precision: medium

notes: test