defaults:
  - _default
  - _self_

hydra:
  job:
    name: test
  sweeper:
    # standard grid search
    params:
      seed: 42
      dataset: asia  # asia / sachs / insurance
      model: cbm  # cbm / cem
      loss: weighted
      loss.concept_weight: 8
      loss.task_weight: 1

dataset:
  batch_size: 4096

model:
  optim_kwargs:
    lr: 0.01
  latent_encoder_kwargs:
    hidden_size: 128
    n_layers: 3
    activation: leaky_relu
    dropout: 0.
  # embedding_size: 4  # for embedding models

metrics:
  summary_metrics: true
  perconcept_metrics: true # true or ${dataset.default_task_names}

trainer:
  # logger: wandb
  max_epochs: 2000
  patience: 50

matmul_precision: medium

notes: test